name: Commit Date Committer

on:
  push:
    branches:
      - gh-pages
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: run commit date reader
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run commitCommitter
      
      - name: remote setting git url
        run: git remote set-url origin https://github.com/schiffke/ghpages_try
      - name: set user email
        run: git config --global user.email "Nick.Schiffke@yahoo.com"
      - name: set user name
        run: git config --global user.name "Nick Schiffke"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add ./src/javascript/date.json
      - name: commit changed files
        run: git commit -m "Auto updating date.json"
      - name: fetch from gh-pages
        run: git fetch origin gh-pages
      - name: push code to gh-pages
        run: git push origin HEAD:gh-pages

   
